### PR TITLE
🔧 build: add .nvmrc file with LTS version

### PR DESCRIPTION
**Pull request by Asuka109**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [x] 🔨 chore
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Add .nvmrc file to setup Node.js with fnm automatically.

Refer to: https://github.com/Schniz/fnm?tab=readme-ov-file#shell-setup

### CODE REVIEW

**Comment by arvinxx** [comment]
why 18? not 20?

**Comment by Asuka109** [comment]
> why 18? not 20?

Just never try that. Do you think we can use `lts/iron`?

**Comment by arvinxx** [comment]
> > why 18? not 20?
> 
> Just never try that. Do you think we can use `lts/iron`?

I’m not sure, but the PR say "with LTS version"

by now the LTS is 20

image

**Comment by Asuka109** [comment]
@arvinxx  Node.js 18 is one of the lts versions and will be supported as a long-term version until April 2025.

It appears you're not very experienced with using version 20 either. How about setting it to 18 for now?

https://nodejs.org/en/about/previous-releases#release-schedule
image

**Comment by arvinxx** [comment]
Ok

**Review by arvinxx — APPROVED** [review]

**Pull request merged**
