### PR TITLE
✨ feat: support authentik as sso

### PR DESCRIPTION
**Pull request by RealTong**
#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
Add Authentik as the SSO Provider
Support multi SSO provider

### CODE REVIEW

**Review by arvinxx — APPROVED** [review]
Sorry for the late review. this PR LGTM, I will merge it. Thanks for your contribution!

**Comment by arvinxx** [comment]
@RealTong plz rebase the main branch~

**Comment by RealTong** [comment]
I apologize for the confusion caused by my improper Git operations, which may have resulted in a messy commit history. As I am still learning Git, I might have made some mistakes in synchronizing with the upstream repository. If this has caused any inconvenience, please feel free to close this Pull Request. I will re-submit a new Pull Request after properly aligning my branch with the upstream codebase.

**Comment by arvinxx** [comment]
@RealTong It's ok, I can squash the commit.

**Pull request merged**
