### PR TITLE
:sparkles: feat(llm): support Ollama AI Provider (local llm)

### PR DESCRIPTION
**Pull request by sjy**
#### 💻 变更类型 | Change Type

- [x] ✨ feat support local llm via ollama (openai compatible) 

#### 📝 补充信息 | Additional Information

Refs #1283

- [x] Need to wait for the ollma PR merged this https://github.com/ollama/ollama/pull/2376/files
- [x] Which open source models are listed under Ollama by default ( currently is Mistral and Llama2 and Qwen)
- [x] Add visible control via server config (env var control)
- [x] Add form field so that user can select customized model  (leverage the capability of Ollama)
image
image

### CODE REVIEW

**Comment by arvinxx** [comment]
@sjy A great PR! 👏👏 

I think there is two issue we should discuss:

1. Ollama only support local LLM, it means that we shouldn't display it when user deploy with Docker/Vercel or other platform.So I think we should hide Ollama setttings when there is no ENV of Ollama. Or we need to implement this feature: https://github.com/lobehub/lobe-chat/discussions/1257 ,  call LLM from browser.
2. I find that ollama has it's own dev kit: [ollama-js](https://github.com/ollama/ollama-js). why not use this?

**Comment by arvinxx** [comment]
I have tried with my MacBook Pro, the speed is really amazing. cc @cocobeach


https://github.com/lobehub/lobe-chat/assets/28616219/cb7002af-dd03-4587-8eac-171cbdf96f9d

**Comment by sjy** [comment]
> @sjy A great PR! 👏👏 
> 
> I think there is two issue we should discuss:
> 
> 1. Ollama only support local LLM, it means that we shouldn't display it when user deploy with Docker/Vercel or other platform.So I think we should hide Ollama setttings when there is no ENV of Ollama. Or we need to implement this feature: https://github.com/lobehub/lobe-chat/discussions/1257 ,  call LLM from browser.
> 2. I find that ollama has it's own dev kit: [ollama-js](https://github.com/ollama/ollama-js). why not use this?

1. A really good point. I will add some visible logic then. For the 1257 feat, I think I need more context 
2. We can use ths js sdk either. But the latest version introduced the opai compatible feature and when looking around the existing implemention of existing none-openai modle providers are also implemented with the openai js sdk, I dont know if we need to follow some guiline when add provider which can implemented by multiple ways just like such case here. BTW. the curent ollama api are only partial compatible with openai api, bit the js dev kit is announced containing all features

**Comment by cocobeach** [comment]
> I have tried with my MacBook Pro, the speed is really amazing. cc @cocobeach
> 
> 
> 
> 
> 
> https://github.com/lobehub/lobe-chat/assets/28616219/cb7002af-dd03-4587-8eac-171cbdf96f9d
> 
> 
> 
> 

That is truly impressive, can't wait to test it, I only have a i9 8 cores and 32gb or ram so I doubt it will run that fast, I can run Solar reasonably well, I find the open source models less "lazy" than gpt4 that seems unbothered to write code without placeholders. What spec is your MacBook, it is indeed mighty fast? 
Well done thanks!!! 🙏

**Comment by arvinxx** [comment]
> For the 1257 feat, I think I need more context

I think this PR doesn't need to consider #1257, I will do it later. This PR just need to focus on the Ollama Provider.

Beside the visible control, I think there should be another field for the custome models in Ollama. It may be the same as OpenAI's custom models. So then users can add their own local models.

**Comment by arvinxx** [comment]
> What spec is your MacBook, it is indeed mighty fast?

My Macbook Pro is a M1 Max 16", 64GB RAM.

**Comment by cocobeach** [comment]
> > What spec is your MacBook, it is indeed mighty fast?
> 
> My Macbook Pro is a M1 Max 16", 64GB RAM.

It's is impressive in speed, the x86 is a bit slower.
Well done! 
Thanks for implementing Ollama so quickly! 😀😀😀

**Comment by tisfeng** [comment]
Looking forward to this new feature to be able to use Ollama local models.

**Comment by sjy** [comment]
> #### 💻 变更类型 | Change Type
> * [x]  ✨ feat support local llm via ollama (openai compatible)
> * [ ]  🐛 fix
> * [ ]  ♻️ refactor
> * [ ]  💄 style
> * [ ]  🔨 chore
> * [ ]  ⚡️ perf
> * [ ]  📝 docs
> 
> #### 🔀 变更说明 | Description of Change
> Support Ollama as an AI Model Provider
> 
> * close [[Request] Local LLM SUPPORT #1281](https://github.com/lobehub/lobe-chat/issues/1281)
> * close [[Request]  local models #1048](https://github.com/lobehub/lobe-chat/issues/1048)
> * close [[Request] LLM 适配 #151](https://github.com/lobehub/lobe-chat/issues/151)
> 
> #### 📝 补充信息 | Additional Information
> Refs #1283
> 
> * [x]  Need to wait for the ollma PR merged this https://github.com/ollama/ollama/pull/2376/files
> * [ ]  Update i18n translation
> * [x]  Which open source models are listed under Ollama by default ( currently is Mistral and Llama2, add Qwen to the default list)

**Comment by sjy** [comment]
> > For the 1257 feat, I think I need more context
> 
> I think this PR doesn't need to consider #1257, I will do it later. This PR just need to focus on the Ollama Provider.
> 
> Beside the visible control, I think there should be another field for the custome models in Ollama. It may be the same as OpenAI's custom models. So then users can add their own local models.
> 
> As for the ollama sdk, I prefer your current implement after investigating the ollama js sdk, it current don't [support browser](https://github.com/ollama/ollama-js/issues/13) by now. So we can't use it when working on #1257. Besides, the all LLM providers are working on the way to be compatible with OpenAI's API schema. Beside Ollama, there are Zhipu AI（智谱)、 Moonshot Ai(月之暗面) and so on. So we can support them very fast.
> 
> Therefore, I think it's better to just use OpenAI sdk.

@arvinxx, updated, BTW, Qwen model is added to the default list when enable Ollam,  please help review the changes ~

**Comment by arvinxx** [comment]
@sjy It's great 👍. And let me take over the rest task~

**Pull request merged**
