### PR TITLE
[fix]ollama run in other port cannot connect

### PR DESCRIPTION
**Pull request by zynfly**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

ollama run in other port cannot connect

@[zynfly](https://github.com/lobehub/lobe-chat/commits?author=zynfly)
zynfly committed 1 minute ago

#### 📝 补充信息 | Additional Information

nothing.

### CODE REVIEW

**Comment by arvinxx** [comment]
ollama use host, so don't use endpoint directly

**Comment by zynfly** [comment]
I looked at the source code of the ollama library, and the host should actually be the endpoint, because its port information comes from this parameter, otherwise it will only access the default port.

**Comment by arvinxx** [comment]
@zynfly but what if the user  use with `127.0.0.1:11434/v1` ?

**Comment by arvinxx** [comment]
@zynfly please try with the `0.149.0` and then check whether it works for you?

**Comment by zynfly** [comment]
> @zynfly but what if the user  use with `127.0.0.1:11434/v1` ?

just http://127.0.0.1:11434

**Pull request closed without merging**
