### PR TITLE
🐛 fix: fix a corner case of `tools_call` with empty object

### PR DESCRIPTION
**Pull request by hezhijie0327**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [X] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

优化 Stream 流中 `content` 有内容时的判定优先级

#### 📝 补充信息 | Additional Information

理论上能修复 https://github.com/lobehub/lobe-chat/pull/3883#issuecomment-2348524889 中提到的这种情况，待验证

### CODE REVIEW

**Comment by arvinxx** [comment]
得让他把 stream 拿出来，然后加个单测

**Comment by arvinxx** [comment]
明确了解不了，https://github.com/lobehub/lobe-chat/issues/3983#issuecomment-2351678496

**Comment by abix5** [comment]
Hey guys, can we already merge this pull request and fix the bug?

**Comment by hezhijie0327** [comment]
@abix5 can share then steam here? From your screenshot seems not the same as that issue

**Comment by abix5** [comment]
Yes, of course, here's the stream. None of the models outputs the result to the chat

o1:
```
{
    "id": "chatcmpl-A7plh0NuZU9XxQTetkRfSkx4eqXUu",
    "object": "chat.completion",
    "created": 1726430657,
    "model": "o1-preview-2024-09-12",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "Hello! How can I assist you today?",
                "name": "",
                "function_call": null,
                "tool_calls": [],
                "tool_call_id": ""
            },
            "finish_reason": "stop",
            "logprobs": null
        }
    ],
    "usage": {
        "prompt_tokens": 9,
        "completion_tokens": 277,
        "total_tokens": 286
    },
    "system_fingerprint": "fp_6c67577ad8"
}
```

4o:
```
...
data: {"id":"chatcmpl-A7pokGUqSov0JuMkhiHhWU9GRtAgJ", "object":"chat.completion.chunk", "created":1726430846, "model":"gpt-4o-2024-05-13", "choices":[{"index":0, "delta":{"content":" today", "role":"", "tool_calls":[]}, "finish_reason":"", "logprobs":""}], "prompt_annotations":[{"prompt_index":0, "content_filter_results":null}]}

data: {"id":"chatcmpl-A7pokGUqSov0JuMkhiHhWU9GRtAgJ", "object":"chat.completion.chunk", "created":1726430846, "model":"gpt-4o-2024-05-13", "choices":[{"index":0, "delta":{"content":"?", "role":"", "tool_calls":[]}, "finish_reason":"", "logprobs":""}], "prompt_annotations":[{"prompt_index":0, "content_filter_results":null}]}

```

**Comment by hezhijie0327** [comment]
Your API is from OpenAI or other provider?

**Comment by abix5** [comment]
OpenAI, however, uses a corporate proxy to it. But the requests are not modified.

**Comment by hezhijie0327** [comment]
Have you try current latest version? From stream seems no issue, basicly same as mine, and it's working
```
{
  "id": "chatcmpl-tmkz20OFTPSgBt4gzAI6FO2hZkpWh",
  "object": "chat.completion",
  "created": 1726433509,
  "model": "o1-mini-2024-09-12",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! Great to hear from you. How can I assist you today?",
        "refusal": null
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 154,
    "total_tokens": 163,
    "completion_tokens_details": {
      "reasoning_tokens": 128
    }
  },
  "system_fingerprint": "fp_3cae7da8eb"
}
```
```
data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"role":"assistant","content":"","refusal":null},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":"Hello"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":"!"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":" How"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":" can"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":" I"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":" assist"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":" you"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":" today"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{"content":"?"},"logprobs":null,"finish_reason":null}]}

data: {"id":"chatcmpl-BHoEyWJE6Z1dQRlhE5Kx9qAhT9BNu","object":"chat.completion.chunk","created":1726433739,"model":"gpt-4o-mini-2024-07-18","system_fingerprint":"fp_483d39d857","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}

data: [DONE]
```
image

**Comment by hezhijie0327** [comment]
Found the cause, catch by `if (item.delta?.tool_calls) {`
image

**Comment by hezhijie0327** [comment]
@abix5 can build on local and have a test?

**Review by arvinxx — APPROVED** [review]
LGTM

**Comment by abix5** [comment]
It worked, thank you very much.

**Pull request merged**
