### PR TITLE
💄 style: disable chunking button for unsupported files

### PR DESCRIPTION
**Pull request by khanhduyvt0101**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change
Disable chunking button for unsupported files

### CODE REVIEW

**Comment by khanhduyvt0101** [comment]
Hi @arvinxx , please consider this PR and merge it man!

**Comment by khanhduyvt0101** [comment]
Hi @arvinxx , Could you help me check this PR?

**Comment by arvinxx** [comment]
take care of multi chunking: 

image

**Comment by khanhduyvt0101** [comment]
I just updated base on your feedback @arvinxx

**Comment by arvinxx** [comment]
I think just disable the batch chunking is not good UX way. If I have 100 files of 99 PDF and 1 image, it's really bad experience that I can't skip this 1 image. Better idea is just skip the unsupported files and batch chunk for the left files.

**Comment by khanhduyvt0101** [comment]
> I think just disable the batch chunking is not good UX way. If I have 100 files of 99 PDF and 1 image, it's really bad experience that I can't skip this 1 image. Better idea is just skip the unsupported files and batch chunk for the left files.

Hi @arvinxx , I updated code base on your review

**Comment by khanhduyvt0101** [comment]
Hi @arvinxx , Could you please help me re-consider this PR?

**Comment by arvinxx** [comment]
@khanhduyvt0101 I'm on vocation of  the Chinese National Day. I will check it at 10.10

**Review by arvinxx — APPROVED** [review]
LGTM now. Thanks for your contribution!

**Pull request merged**
