### PR TITLE
🐛 fix: fix normalizeLocale with first matching locale

### LINKED ISSUE #1886: [Bug] Application error: a server-side exception has occurred
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Firefox

### 🐛 Bug Description

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 144739034
This error appearing on my both OS : Windows11 23H1 and Linux Fedora 39

### 🚦 Expected Behavior

A correct Launching of the web app from docker like yesterday 

### 📷 Recurrence Steps

Pulling docker
Running image from docker desktop or terminal (tried multiple port and the default one)

### Server Logs
```
2024-04-03 13:52:05    ▲ Next.js 14.1.4
2024-04-03 13:52:05    - Local:        http://localhost:3210
2024-04-03 13:52:05    - Network:      http://0.0.0.0:3210
2024-04-03 13:52:05 
2024-04-03 13:52:05  ✓ Ready in 73ms
2024-04-03 13:52:20 Error: Cannot find module './fr.js'
2024-04-03 13:52:20     at /app/.next/server/chunks/19750.js:1:7954
2024-04-03 13:52:20     at runNextTicks (node:internal/process/task_queues:60:5)
2024-04-03 13:52:20     at listOnTimeout (node:internal/timers:540:9)
2024-04-03 13:52:20     at process.processTimers (node:internal/timers:514:7)
2024-04-03 13:52:20     at async H (/app/.next/server/chunks/19750.js:226:7754)
2024-04-03 13:52:20     at async eu (/app/.next/server/chunks/19750.js:226:8477) {
2024-04-03 13:52:20   code: 'MODULE_NOT_FOUND'
2024-04-03 13:52:20 }
2024-04-03 13:52:20 [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2024-04-03 13:52:20   digest: '144739034'
2024-04-03 13:52:20 }
2024-04-03 13:52:20 Error: Cannot find module './fr.js'
2024-04-03 13:52:20     at /app/.next/server/chunks/19750.js:1:7954
2024-04-03 13:52:20     at async H (/app/.next/server/chunks/19750.js:226:7754)
2024-04-03 13:52:20     at async eu (/app/.next/server/chunks/19750.js:226:8477) {
2024-04-03 13:52:20   code: 'MODULE_NOT_FOUND'
2024-04-03 13:52:20 }
2024-04-03 13:52:20 [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2024-04-03 13:52:20   digest: '3869975412'
2024-04-03 13:52:20 }
```

### 📝 Additional Information

_No response_

### PR DESCRIPTION
**Pull request by polynux**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Fix an error where the locale is set to a first part of a locale name. For instance, if we have fr-FR, it will set locale to fr, and will cause en error.

#### 📝 补充信息 | Additional Information

Same issue as #1747 but generalize.

- fix https://github.com/lobehub/lobe-chat/issues/1886
- fix https://github.com/lobehub/lobe-chat/discussions/1779

### CODE REVIEW

**Comment by arvinxx** [comment]
can't do this, or it will case problem like: https://github.com/lobehub/lobe-chat/issues/844 or https://github.com/lobehub/lobe-chat/issues/308

**Comment by polynux** [comment]
So, we can't fix this problem ?
Because unless the navigator language is en, de, it will cause the same error because it load en, despite the fact that translations are available.

I can open an issue if you want

**Comment by arvinxx** [comment]
@polynux the problem is that our locale is `zh-CN`、 `en-US` , when user's navigator is `en`, we need to normailze it to `en-US`. 

So as the #1747 issue

**Comment by polynux** [comment]
Yeah i understand this problem.

I looked at the issues you mentioned, and my commit don't break those things i guess.

In my commit, if you look at src/locales/resources.ts, i iterate though the list of locales.
So if your locale in your navigator is "zh", it will select "zh-CN" since it is the first in "locales" list beginning with "zh".
It is the same for "en", "de", etc...
And in the case where no locale is found, it will default to "en-US", as it is right now.

I'm using deepl to translate issues in chinese, so feel free to correct me if i missed something.

**Comment by polynux** [comment]
image
You can see on my screenshot, that i have selected "zh" as the default language for my browser.

image
Or here with "en" english.

image
Here is "fr-FR" "Français (France)"

image
And lastly with just "fr"

**Comment by arvinxx** [comment]
@polynux sorry for the late, I think your code is right and can work well. And I'll merge it. Thanks for your contribution!

**Comment by arvinxx** [comment]
I have update the code and then it works well now.

**Pull request merged**
