### PR TITLE
💄 style: Update token tag popover style

### PR DESCRIPTION
**Pull request by canisminor1990**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

image

## Summary by CodeRabbit

- **New Features**
  - Introduced new translations for token details in multiple languages:
    - Spanish (Spain)
    - French
    - Italian (Italy)
    - Japanese
    - Korean
    - Dutch (nl-NL)
    - Polish
    - Portuguese (Brazil)
    - Russian
    - Turkish
    - Vietnamese
    - Chinese (Simplified)
    - Chinese (Traditional)

- **Improvements**
  - Updated existing translations for token details in multiple languages:
    - Arabic
    - Bulgarian
    - German
    - English (US)
    - Bulgarian (bg-BG)
    - Chinese (Simplified)
    - Chinese (Traditional)
    - Japanese
    - Korean
    - Dutch (nl-NL)
    - Polish
    - Portuguese (Brazil)
    - Russian
    - Spanish (Spain)
    - French
    - Italian (Italy)
    - Turkish
    - Vietnamese

### CODE REVIEW

**Comment by arvinxx** [comment]
image

空状态展示有问题

**Comment by canisminor1990** [comment]
> image
> 空状态展示有问题

修了

**Comment by arvinxx** [comment]
image

我感觉这个字体没之前的好看。有点太像代码了

**Comment by canisminor1990** [comment]
> image
> 我感觉这个数字没之前的好看。有点太像代码了

主要想和 token tag 里的字体统一

**Comment by arvinxx** [comment]
@canisminor1990 token tag用那个字体也不好看，看着像有衬线的

**Comment by canisminor1990** [comment]
@arvinxx

**Review by arvinxx — APPROVED** [review]
LGTM

**Pull request merged**
