### PR TITLE
💄 style: Add displaying the message "Reset Successfully."

### PR DESCRIPTION
**Pull request by RubuJam**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change
Upon completion of the reset process, a pop-up window will appear, displaying the message "Reset Successfully."
重置成功后，会弹窗显示“已成功重置”

### CODE REVIEW

**Comment by RubuJam** [comment]
请问该执行什么命令，让`locales/zh-CN/setting.json`里添加的内容，在其它语言版本对应文件里翻译并修改（项目在CodeSpace里运行）
@arvinxx

**Comment by arvinxx** [comment]
Please run `npm run i18n`

**Comment by RubuJam** [comment]
> npm run i18n

请问` ERROR  Translate failed, TypeError: Cannot read properties of undefined (reading 'message') `该怎么解决，我尝试了很多次，都是这样

Please tell me how to solve ` ERROR Translate failed, TypeError: Cannot read properties of undefined (reading 'message') `. I have tried many times, but it is still like this.

**Comment by RubuJam** [comment]
> Please run `npm run i18n`

已经翻译完毕，用了这么长时间是因为我设置的`OPENAI_PROXY_URL`路径缺少`/v1`，导致一直报错` ERROR  Translate failed, TypeError: Cannot read properties of undefined (reading 'message') `，刚刚才发现问题

The translation has been completed. It took so long because the `OPENAI_PROXY_URL` path I set lacked `/v1`, which caused the error `ERROR Translate failed, TypeError: Cannot read properties of undefined (reading 'message')`. I just discovered the problem.

**Comment by arvinxx** [comment]
怎么好像 success 的调用没了

**Comment by RubuJam** [comment]
> 怎么好像 success 的调用没了

这个吗？https://github.com/lobehub/lobe-chat/blob/de84a0dd254f00995ed5e12ac001d26f03ecf720/src/app/settings/common/Common.tsx#L71

This one? https://github.com/lobehub/lobe-chat/blob/de84a0dd254f00995ed5e12ac001d26f03ecf720/src/app/settings/common/Common.tsx#L71

**Comment by arvinxx** [comment]
哦 看到了，应该是我之前手机上看到的不全

**Review by arvinxx — APPROVED** [review]
LGTM, Thanks for your contribution!

**Pull request merged**
