### PR TITLE
✨ feat: Use current model to generate summary title

### PR DESCRIPTION
**Pull request by davidreis97**
#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Use the current model to generate a summary title for the topic

### CODE REVIEW

**Comment by MapleEve** [comment]
这个功能我记得在RFC里面有提到，是要用户在设置页自定义使用一个模型做标题自动生成
相同的产品比如NextChat一类经常被人诟病的问题就是用了很贵的模型（MJ，TTS一类）然后又被自动请求生成标题

**Comment by arvinxx** [comment]
I think it's a good method to use current model to summary the topic. 

But as @MapleEve said, there is a fee issue with this change. So I think this method can be a config for user to choose whether use fixed model or agent's model, or just disable it.

As for this PR. I'm glad to set it as the default option. But the code need some improvement for merge. And I'll add my review soon.

Before merging it, I think I need to add the mode config firstly.

**Comment by arvinxx** [comment]
the relative PR: https://github.com/lobehub/lobe-chat/pull/1902

**Comment by arvinxx** [comment]
hi, we support systemAgent to achieve summary title , do you think it still need a current model summary ?

**Pull request closed without merging**
