### PR TITLE
💄 style:  add Moonshot Kimi Reverse model to Moonshot model provider.

### PR DESCRIPTION
**Pull request by MapleEve**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

https://github.com/sherlcok314159/reverse-kimi

Support one-api or new-api call.

#### 📝 补充信息 | Additional Information

N/A

### CODE REVIEW

**Comment by MapleEve** [comment]
image

支持简单的 base64 转图识别、链接内容解析、文件pdf解析
支持互联网搜索结果展示

**Comment by MapleEve** [comment]
image

**Comment by arvinxx** [comment]
LGTM, have you run with test on local? The test ci is still failed due to bun@1.0.33 bug

**Comment by MapleEve** [comment]
> LGTM, have you run with test on local? The test ci is still failed due to bun@1.0.33 bug

I've run via `yarn dev`, and via custom model also fine.

Will merge upstream/main to this pr branch soon.

**Comment by arvinxx** [comment]
提了个建议：https://github.com/sherlcok314159/reverse-kimi/issues/10，看下作者反馈

**Pull request merged**
