### PR TITLE
✨ feat: fully support ollama with browser request mode

### LINKED ISSUE #1618: lobe-chat fails to use ollama
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
  "error": {
    "headers": {
      "content-length": "18",
      "content-type": "text/plain",
      "date": "Mon, 18 Mar 2024 00:50:25 GMT"
    },
    "stack": "Error: 404 404 page not found\n    at eP.generate (/app/.next/server/edge-chunks/261.js:4:1754)\n    at sp.makeStatusError (/app/.next/server/edge-chunks/261.js:4:13675)\n    at sp.makeRequest (/app/.next/server/edge-chunks/261.js:4:14598)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async J.chat (/app/.next/server/edge-chunks/353.js:1:11187)\n    at async eh (/app/.next/server/edge-chunks/353.js:1:18173)\n    at async /app/.next/server/edge-chunks/212.js:6:64195\n    at async O.execute (/app/.next/server/edge-chunks/212.js:6:61088)\n    at async O.handle (/app/.next/server/edge-chunks/212.js:6:65462)\n    at async ey.handler (/app/.next/server/edge-chunks/212.js:7:31644)",
    "status": 404
  },
  "endpoint": "http://192.168.***.6:****/",
  "provider": "ollama"
}

### 🚦 Expected Behavior

_No response_

### 📷 Recurrence Steps

_No response_

### 📝 Additional Information

image

### LINKED ISSUE #1619: [Bug] Ollama cannot connect after Lobechat updating to 0.137.0 and later versions
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

This error occurs when connecting
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com/settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/ /api/tags'. This request has been blocked; the content must be served over HTTPS.

X is hidden

`Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
S @ 24880-a1352162eb55ff0d.js:87
m @ 24880-a1352162eb55ff0d.js:87
L @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
onClick @ page-c1f34bbd8715202e.js:1
ei @ 24880-a1352162eb55ff0d.js:3
aS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
aN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sw @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
oK @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
iL @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uE @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
S @ 24880-a1352162eb55ff0d.js:87
m @ 24880-a1352162eb55ff0d.js:87
L @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
onClick @ page-c1f34bbd8715202e.js:1
ei @ 24880-a1352162eb55ff0d.js:3
aS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
aN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sw @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
oK @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
iL @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uE @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
S @ 24880-a1352162eb55ff0d.js:87
m @ 24880-a1352162eb55ff0d.js:87
L @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
onClick @ page-c1f34bbd8715202e.js:1
ei @ 24880-a1352162eb55ff0d.js:3
aS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
aN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sw @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
oK @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
iL @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uE @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
S @ 24880-a1352162eb55ff0d.js:87
m @ 24880-a1352162eb55ff0d.js:87
L @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
onClick @ page-c1f34bbd8715202e.js:1
ei @ 24880-a1352162eb55ff0d.js:3
aS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
aN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sw @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
oK @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
iL @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uE @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
S @ 24880-a1352162eb55ff0d.js:87
m @ 24880-a1352162eb55ff0d.js:87
L @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
onClick @ page-c1f34bbd8715202e.js:1
ei @ 24880-a1352162eb55ff0d.js:3
aS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
aN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sw @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
oK @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
iL @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uE @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
setTimeout (async)
onErrorRetry @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
await in (anonymous) (async)
(anonymous) @ 24880-a1352162eb55ff0d.js:87
S @ 24880-a1352162eb55ff0d.js:87
m @ 24880-a1352162eb55ff0d.js:87
L @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
onClick @ page-c1f34bbd8715202e.js:1
ei @ 24880-a1352162eb55ff0d.js:3
aS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
aN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sw @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
(anonymous) @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
oK @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
iL @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
sN @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uE @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
uS @ 3384b7c8-0c69b496d2309478.js?__WB_REVISION__=d3pya9ErvVpjNgFDpYxz3:1
24489-71bdeaddd1b002b1.js:1 Mixed Content: The page at 'https://xxx.xxxxx.com//settings/llm' was loaded over HTTPS, but requested an insecure resource 'http://192.168.x.x:11434/api/tags'. This request has been blocked; the content must be served over HTTPS.
o @ 24489-71bdeaddd1b002b1.js:1
i @ 24489-71bdeaddd1b002b1.js:1
list @ 24489-71bdeaddd1b002b1.js:1
getModels @ page-c1f34bbd8715202e.js:1
i @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
(anonymous) @ 24880-a1352162eb55ff0d.js:87
e.isPaused.e.onErrorRetry.retryCount @ 24880-a1352162eb55ff0d.js:87
`

### 🚦 Expected Behavior

_No response_

### 📷 Recurrence Steps

_No response_

### 📝 Additional Information

Because ollama's host is run separately from lobechat. One host is responsible for computing and the other is responsible for the ui interface of lobechat. It cannot be solved through reverse proxy processing. Please fix it!~

### LINKED ISSUE #1633: I don't use ollama in lobechat
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

WechatIMG174
WechatIMG173
image

### 🚦 期望结果

first, i can run 127.17.0.1:11434,but i don't use ollama in lobechat.my ollama run use OLLAMA_HOST=0.0.0.0 ollama serve,lobechat run use docker run -d -p 3210:3210 -e OLLAMA_PROXY_URL=http://192.168.31.6:11434 lobehub/lobe-chat.

### 📷 复现步骤

_No response_

### 📝 补充信息

_No response_

### LINKED ISSUE #1665: [Bug] Can't use Ollama custom model
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

Got this when trying to use ollama custom model:
```
{
  "error": {
    "headers": {
      "content-length": "18",
      "content-type": "text/plain",
      "date": "Thu, 21 Mar 2024 08:38:46 GMT"
    },
    "stack": "Error: 404 404 page not found\n    at eP.generate (/app/.next/server/edge-chunks/405.js:4:1754)\n    at sp.makeStatusError (/app/.next/server/edge-chunks/405.js:4:13675)\n    at sp.makeRequest (/app/.next/server/edge-chunks/405.js:4:14598)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async V.chat (/app/.next/server/edge-chunks/953.js:1:11226)\n    at async eA (/app/.next/server/edge-chunks/953.js:1:20149)\n    at async /app/.next/server/edge-chunks/212.js:6:64195\n    at async O.execute (/app/.next/server/edge-chunks/212.js:6:61088)\n    at async O.handle (/app/.next/server/edge-chunks/212.js:6:65462)\n    at async ey.handler (/app/.next/server/edge-chunks/212.js:7:31644)",
    "status": 404
  },
  "endpoint": "http://ollama:****/",
  "provider": "ollama"
}
```

### 🚦 Expected Behavior

It should be called successfully and return response

### 📷 Recurrence Steps

1. Compose up the app
2. Select Ollama's custom model
3. Send message
4. Got error

### 📝 Additional Information

Here is my docker-compose.yaml:
```
version: '3.8'
 
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobechat
    restart: always
    ports:
      - '3210:3210'
    user: root
    environment:
      # OPENAI_API_KEY: sk-xxxx
      # OPENAI_PROXY_URL: https://api-proxy.com/v1
      OLLAMA_PROXY_URL: http://host.docker.internal:11434/v1
      ACCESS_CODE: lobe66
  
  ollama:
    volumes:
      - /home/vuongnt/workspace/mimi/models:/ollama

    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
```

I also try to config in setting but not working:
Screenshot 2024-03-21 at 15 46 12
Here is my ollama model (access container):
Screenshot 2024-03-21 at 15 47 05

### LINKED ISSUE #1821: [Bug] 最新版本的ollamo不兼容【从0.1.28升级到0.1.30】
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

其他 continue.dev 在 Ollama 更新前后都可以使用，但是lobe-chat在ollama跟新晚后现实如下：
【continue.dev和lobe-chat和Ollama在同一个局域网】

image

### 🚦 Expected Behavior

_No response_

### 📷 Recurrence Steps

_No response_

### 📝 Additional Information

_No response_

### LINKED ISSUE #1933: Feedback for “在 LobeChat 中使用 Ollama”
按教程容器部署后，始终无法连接本地Ollama的端口，是需要特殊的配置吗？

确认Ollama运行及服务正常。

图片

### LINKED ISSUE #2091: [Bug] lob-chat docker 按步骤操作无法访问 ollama
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

ollama 是运行正常，能在另一个节点上正常访问
image
lobehub docker 运行正常
image

image
image

### 🚦 Expected Behavior

_No response_

### 📷 Recurrence Steps

_No response_

### 📝 Additional Information

_No response_

### LINKED ISSUE #2144: [Bug] lobechat本地启动连接ollama无法访问
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

如图，在浏览器中正常启动了ollama的服务
image
在lobechat中已经配置了ollama的服务，并且检查通过
image
但是在对话的时候报错
image

### 🚦 期望结果

期望正常对话结果

### 📷 复现步骤

ollama和lobechat都是本地开发环境启动，没有使用dock启动lobechat

### 📝 补充信息

_No response_

### LINKED ISSUE #2164: [Bug] macOS Ollama 模型检查通过，但对话失败 CORS 报错
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

Ollama 模型检查通过，但对话失败 CORS 报错。

之前这里报过这个问题  https://github.com/lobehub/lobe-chat/discussions/728#discussioncomment-9196340 ，模型检查都会失败，后面参考这里 [在 Mac 上设置环境变量](https://lobehub.com/zh/docs/self-hosting/examples/ollama#%E5%9C%A8-mac-%E4%B8%8A%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)，模型检查成功了，但对话还是失败 CORS，请问该如何解决？

我搜了一下，很多其他系统用户都提到了这个问题 https://github.com/lobehub/lobe-chat/issues/2144 。

image

image

### 🚦 期望结果

我的服务部署在 Vercel，希望能在 Mac 本地使用 Ollama 模型。

### 📷 复现步骤

_No response_

### 📝 补充信息

_No response_

### LINKED ISSUE #2173: [Bug] 自动拉取 Ollama 模型的问题 （非本地部署）
### 💻 系统环境

macOS

### 📦 部署环境

Docker

### 🌐 浏览器

Chrome

### 🐛 问题描述

image
如果我的 Ollama 部署在非 LobeChat 的机器上，局域网里面另外一台 AI 工作站。这个拉取模型的功能就会一直请求本地的 api

### 🚦 期望结果

 读取正确的模型端点 api 获取到真实下载进度

### 📷 复现步骤

系统架构：
1. 异地访问Lobechat
2. Lobechat 和 Ollama 部署在不同的机器中

### 📝 补充信息

_No response_

### PR DESCRIPTION
**Pull request by arvinxx**
#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

- fix #2164 
- fix #2144
- fix #2091 
- fix #1933 
- fix #1821 
- fix #1633
- fix #1619 
- fix #1618
- fix #2173
- fix #1665 
- fix #2172
- fix #1486 
- close https://github.com/lobehub/lobe-chat/pull/2157

#### 📝 补充信息 | Additional Information

refs: https://github.com/lobehub/lobe-chat/discussions/2169

### CODE REVIEW

**Comment by MapleEve** [comment]
image
应该不是同一个问题，我要单独提个 Issue 吗

**Comment by arvinxx** [comment]
@MapleEve 应该是同一个

**Comment by MapleEve** [comment]
> @MapleEve 应该是同一个

也加进来了

**Comment by geniucker-dev** [comment]
是否可以在桌面客户端也加入Client Request Mode（当连接到self-hosted server时）

**Pull request merged**
