### PR TITLE
Creating self-hosting documents repocloud.mdx

### PR DESCRIPTION
**Pull request by cosark**
- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [x] 📝 docs

#### 🔀 变更说明 | Description of Change

Adding deployment documentation for RepoCloud as requested :)

### CODE REVIEW

**Comment by arvinxx** [comment]
@cosark can you provider a svg logo of repocloud ?

**Comment by cosark** [comment]
> @cosark can you provider a svg logo of repocloud ?

https://d16t0pc4846x52.cloudfront.net/deploy.svg

**Comment by arvinxx** [comment]
@cosark LGTM, If you want to show up the RepoCloud Branding, I think you can add a hero image like this:

image

like this doc: https://github.com/lobehub/lobe-chat/blob/8c82e3d7d7b88776d2d46e1ab44d3b14de16276d/docs/usage/providers/ollama/gemma.mdx#L5-L10

If not , I will merge it.

**Comment by cosark** [comment]
LGTM to merge! (Additional branding graphics are not available unfortunately.)

**Review by arvinxx — APPROVED** [review]
I'm glad to merge it, Thanks for your work! @cosark

**Comment by cosark** [comment]
Looks like users are unable to find the link anywhere?

**Comment by cosark** [comment]
There's currently no way for the users to see the link?

**Comment by arvinxx** [comment]
@cosark  now you can find it here: https://chat-docs.lobehub.com/en/self-hosting/platform/repocloud

**Pull request merged**
