### PR TITLE
allow deploy to Zeabur as serverless function and update readme accordingly

### PR DESCRIPTION
**Pull request by AHA1GE**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ x] 🔨 chore
- [ ] ⚡️ perf
- [x ] 📝 docs

#### 🔀 变更说明 | Description of Change
allow deploy to Zeabur as serverless function and update readme accordingly

#### 📝 补充信息 | Additional Information
Deploying to Zeabur as serverless function may impact performance and case unexpected behavior!

### CODE REVIEW

**Comment by AHA1GE** [comment]
If the prebuilt image of LobeChat on Zeabur is directly built from the official repository, this PR might inadvertently convert the image into a serverless function image, which may not be our intention. In such a case, this PR should be closed, and we should encourage users/developers to create their own zbpack.json in their own fork.

**Comment by arvinxx** [comment]
@MichaelYuhe maybe you can check it ?

**Comment by MichaelYuhe** [comment]
It's recommended to use prebuilt to deploy Lobe Chat on Zeabur, or through the default containerized way. There is still some problems with serverless next.js on Zeabur such as middlewares and rewrites.

**Comment by arvinxx** [comment]
@AHA1GE better to add this part in docs

**Comment by AHA1GE** [comment]
https://github.com/lobehub/lobe-chat/pull/2787

**Pull request closed without merging**
