### PR TITLE
✨ feat: support the  perplexity provider

### PR DESCRIPTION
**Pull request by gijigae**
#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Added a new model provider, Perplexity, along with the following five models.
image

Corresponding setup section is also added to the Language Model.
image

#### 📝 补充信息 | Additional Information

Perplexity AI requires the value of FrequencyPenalty to be greater than 0. Thus, the default value for FrequencyPenalty has been set to 0.1.

### CODE REVIEW

**Review by arvinxx — APPROVED** [review]
I have run the auto translate ( `npm run 18n`) and update the model list order ( I think pplx model should  rank at first ).

And the rest is LGTM. I'll merge it.

Thanks for your contribution! 👏

**Comment by arvinxx** [comment]
@gijigae Oh I just forgot the document, would you mind to add doucment to guide our users to use the perplexity provider?

**Comment by gijigae** [comment]
> @gijigae Oh I just forgot the document, would you mind to add doucment to guide our users to how to config the perplexity provider?

Thanks for merging @arvinxx ! For the document, should I add a new document file to the `contributing/Basic` directory or adding a new line to the `docs/usage/features/multi-ai-providers.mdx` will suffice? Or both?

**Comment by gijigae** [comment]
Will prepare those documents including a guide for developers to add a new provider. Regarding "can be powered by the gpt and crawler plugin", what does that mean? There are so many things to learn and I like it 😊.

**Comment by arvinxx** [comment]
>  Regarding "can be powered by the gpt and crawler plugin", what does that mean?

@gijigae like this:

LobeChat_LobeChat 技术文档专家_2024-02-22

You can refers it with this link: https://sharegpt.com/c/G0azkMo

the final document here: https://github.com/lobehub/lobe-chat/blob/main/contributing/Internationalization/Add-New-Locale.zh-CN.md

and I run `npm i18n-docs` to translate it from Chinese to English. It's super efficiently.

the agent can find here: https://chat-preview.lobehub.com/market?agent=lobe-chat-developer-document-writer

**Comment by halxjo** [comment]
Hi everyone, I am new here.
I have been a fan of Perplexity.
What I found is that during the reasoning phase of Perplexity, the information was listed very clearly.
However, the final result is:
1. badly formatted, to the extend unreadable.
2. Mixed of languages and symbols displayed looks like gearbages.
3. truncated, I don't think the final response is fully displayed.

Are there any works in progress to fix perplexity outputs?

Thank you all.

**Pull request merged**
