### PR TITLE
💄 style: Add sessionToken input for bedrock model 

### PR DESCRIPTION
**Pull request by khanhduyvt0101**
#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change
✨ feat: Add sessionToken input for bedrock model

### CODE REVIEW

**Comment by arvinxx** [comment]
could you please show the relative infor about sessionToken ?

**Comment by khanhduyvt0101** [comment]
> could you please show the relative infor about sessionToken ?

I updated!
CleanShot 2024-09-09 at 21 05 18@2x

**Comment by arvinxx** [comment]
image

this one should like the custom region, after click to add

**Comment by khanhduyvt0101** [comment]
> image
> this one should like the custom region, after click to add

This is the custom region field, not the red rectangle in your image @arvinxx 
CleanShot 2024-09-10 at 23 37 01@2x

**Comment by arvinxx** [comment]
I mean due to the session token is not a must field, it like the region field should hide the input . after user click the button and then show the input

**Comment by khanhduyvt0101** [comment]
> I mean due to the session token is not a must field, it like the region field should hide the input by default. after user click the button and then show the input

Thank you for your explain, I updated
CleanShot 2024-09-11 at 09 51 25@2x

**Comment by arvinxx** [comment]
@khanhduyvt0101 hi, it looks good to me, please rebase the code and I'll merge it~

**Comment by khanhduyvt0101** [comment]
I reabased! @arvinxx

**Pull request merged**
