### PR TITLE
💄 style: add bedrock claude-3.5-sonnect-v2

### PR DESCRIPTION
**Pull request by 0x2E**
#### 💻 变更类型 | Change Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [x] 💄 style
- [ ] 👷 build
- [ ] ⚡️ perf
- [ ] 📝 docs
- [ ] 🔨 chore

#### 🔀 变更说明 | Description of Change

Add bedrock claude-3.5-sonnect-v2 model.

### CODE REVIEW

**Comment by AnoyiX** [comment]
感觉这个命名为 `Claude 3.5 Sonnet V2` 比较合适，原来的按个模型名字不改

**Comment by 0x2E** [comment]
> 感觉这个命名为 Claude 3.5 Sonnet V2 比较合适，原来的那个模型名字不改

这会与已有的命名策略冲突 https://github.com/lobehub/lobe-chat/pull/4452/files#diff-095fbc8fd968d48041891852ab4de043217416e71dd45ce5209c5f24ffec6193R27

**Comment by arvinxx** [comment]
@0x2E 没问题，Display Name 是可以重复的

**Comment by gemnioo** [comment]
docker lobehub/lobe-chat:v1.26.17  still exist request 'claude-3-5-sonnet-20241022-v2' models but using  region us-east-1. after change the Settings--Lauguage Models-- aws bedrock-- AWS Region to 'us-west-2'

As currently even the Claude 3.5 Sonnet v2 have Cross-region inference in 'us-east-1'

this error shows below:

```
{
  "error": {
    "body": {
      "httpStatusCode": 400,
      "requestId": "",
      "attempts": 1,
      "totalRetryDelay": 0
    },
    "message": "Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.",
    "type": "ValidationException"
  },
  "provider": "bedrock",
  "region": "us-east-1"
}
```

**Comment by gemnioo** [comment]
last version still have aws bedrock claude 3.5 v2 request error.  searched other repositories have same issues

```
Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported
```
https://github.com/danny-avila/LibreChat/discussions/4571
https://github.com/cline/cline/issues/689

even set the region in us-west-2 (cross-region inference support in us-east-1). pls modify the region number in the endpoint

```
To be able to use the latest Sonnet 3.5 from the us-east-1 region, the model inference profile id is 

'us.anthropic.claude-3-5-sonnet-20241022-v2:0', 

it will route the inference to the region where the model is hosted.
https://github.com/danny-avila/LibreChat/discussions/4571#discussioncomment-11114851

```

**Pull request merged**
