### PR TITLE
:sparkles: feat: support mistral as model provider

### PR DESCRIPTION
**Pull request by danielglh**
#### 💻 变更类型 | Change Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] ⚡️ perf
- [ ] 📝 docs

#### 🔀 变更说明 | Description of Change

Added a new model provider, Mistral, along with the 5 models it currently provides.

image

image

image

#### 📝 补充信息 | Additional Information

**Different API Parameters**

According to the official API doc, Mistral API doesn't seem to support these parameters: `presence_penalty, frequency_penalty`. Therefore the implementation needs to pick only the supported parameters and the `presence_penalty, frequency_penalty` settings do not affect Mistral models.

### CODE REVIEW

**Comment by arvinxx** [comment]
@danielglh please rebase the main and solve the conflicts~

**Comment by arvinxx** [comment]
@danielglh I think the code is really clean and great. This time can we bump up the test coverage to 100% for the mistral provider and anthropic provider relative code?

**Comment by danielglh** [comment]
> @danielglh please rebase the main and solve the conflicts~

@arvinxx already did

**Comment by danielglh** [comment]
> @danielglh I think the code is really clean and great. This time can we bump up the test coverage to 100% for the mistral provider and anthropic provider relative code?

For sure. I've already added tests for mixtral (mostly just copied from the perplexity/moonshot tests). Not sure how to check the test coverage of each provider though. @arvinxx

**Comment by danielglh** [comment]
@arvinxx added tests for anthropic and mistral. Hopefully the coverage should be good now.

**Comment by arvinxx** [comment]
plz rebase it

**Comment by danielglh** [comment]
> plz rebase it

@arvinxx done

**Review by arvinxx — APPROVED** [review]
Nice work! LGTM, I'll merge it~ Thanks for your contribution👏

**Pull request merged**
